# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [8]:
import numpy as np
# formula = weight / (height**2) * 730
height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

bmi = weight / (height ** 2) * 730

np.set_printoptions(precision=3)

print(bmi)

print()

print(bmi.reshape(7,1))

[16.866 17.878 18.826 19.715 20.548 21.329 22.062]

[[16.866]
 [17.878]
 [18.826]
 [19.715]
 [20.548]
 [21.329]
 [22.062]]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [9]:
def random_matrix(min_val, max_val, shape=(6,6), data_type=float):
    return np.random.uniform(min_val, max_val, shape).astype(data_type)


print(random_matrix(1,100))
print()
print(random_matrix(1,100,(7,2),data_type=int))

[[46.215 87.944 39.387 89.471  4.961 44.182]
 [39.223 73.972 87.052 32.195 26.921  2.259]
 [52.537 41.496 82.147 81.184 18.524 81.474]
 [34.486 60.741 78.682 21.887 89.888 92.322]
 [ 4.756 73.874 55.05  86.279  3.7   70.238]
 [45.348 70.632 63.806 19.735 12.968 85.696]]

[[45 89]
 [57  9]
 [60 80]
 [ 3 26]
 [20 89]
 [15 25]
 [31 19]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [10]:
import csv
import numpy as np

In [11]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ","):
    data = np.genfromtxt(filename, delimiter= d, skip_header= 1,
                        usecols= np.arange(0,24), invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('files/redsox_2017_hitting.txt')
bs2018 = load_data('files/redsox_2018_hitting.txt')

avg_hits2017 = sum(bs2017["SLG"]) / len(bs2017["SLG"])
avg_hits2018 = sum(bs2018["SLG"]) / len(bs2018["SLG"])

if avg_hits2017 > avg_hits2018:
    print("The RedSox had a better average hits in 2017.")
else:
    print("The RedSox had a better average hits in 2018.")


The RedSox had a better average hits in 2017.
